services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mr_task_guru
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
